### ISSUE TITLE
MS is not parseable due to broken UO import

### ISSUE THREAD

**Issue by matentzn** [HUPO-PSI/psi-ms-CV#138]
See, for example:

```
robot -vvv merge -I http://purl.obolibrary.org/obo/ms.owl -o ms.owl
```

Noticed it here: http://dashboard.obofoundry.org/dashboard/index.html

**Comment by edeutsch** [comment]
So what's the solution?
We've been trying to get these things fixed in UO, but there seems to be no maintenance there

**Comment by matentzn** [comment]
Put some pressure on https://github.com/bio-ontology-research-group/unit-ontology/issues/56 along with other users!

**Comment by mwalzer** [comment]
We had a similar issue - but with the obo file- due to the UO import which made parsers choke. https://github.com/bio-ontology-research-group/unit-ontology/issues/44 got resolved after a while, and obo parses fine now. But the obo won't do much good here, would it? 
@edeutsch we don't use that many metrics and they are all SI? What would it mean if we switched to another (potentially new) ontology for our terms using UO?

**Comment by mobiusklein** [comment]
https://github.com/bio-ontology-research-group/unit-ontology/pull/55 implies it fixes this problem?

**Comment by matentzn** [comment]
Yes, hopefully, but only if it gets merged ;)

**Comment by mobiusklein** [comment]
It was 6-7 hours ago, and now our OWL generating workflow is fixed
