### ISSUE TITLE
CV Term needed for apl file format Andromeda 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#18]
In the mass spectrometer files we need a Cvterm for apl file (peak list file from Andromeda search engine). 

inside here https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000560

**Comment by ypriverol** [comment]
Please @germa as soon as possible.

**Comment by germa** [comment]
Included since version 4.1.14:
[Term]
id: MS:1002995
name: Andromeda:PEP
def: "Posterior error probability of the best identified peptide of the Andromeda search engine." [PSI:PI]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1001143 ! PSM-level search engine specific statistic
relationship: has_domain MS:1002305 ! value between 0 and 1 inclusive
relationship: has_order MS:1002108 ! higher score better

**Comment by ypriverol** [comment]
The term you have added @germa is for the PEP probability of Andromeda. That is cool. But we need a new CV Term for the apl file format inside the mass spectrometer file formats.

**Comment by germa** [comment]
Included in version 4.1.15:
[Term]
id: MS:1002996
name: Andromeda:apl file format
def: "Peak list file format of the Andromeda search engine." [PSI:PI]
is_a: MS:1000560 ! mass spectrometer file format
