### ISSUE TITLE
Need CV term for new thermo FAIMS device 'compensationVoltage'

### ISSUE THREAD

**Issue by jgmeyerucsd** [HUPO-PSI/psi-ms-CV#22]
Thermo recently started selling an ion mobility device that can bolt-on many of its instruments. The resulting files produce a new line in the scan header with the term 'compensationVoltage', which is used to specify the FAIMS setting for that scan. Can we add this term to the controlled vocabulary please?

**Comment by edeutsch** [comment]
Hi Jesse, it’s already there!



https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1001581



Cheers,

Eric





*From:* Jesse G. Meyer <notifications@github.com>
*Sent:* Wednesday, April 17, 2019 8:21 AM
*To:* HUPO-PSI/psi-ms-CV <psi-ms-CV@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [HUPO-PSI/psi-ms-CV] Need CV term for new thermo FAIMS device
'compensationVoltage' (#22)



Thermo recently started selling an ion mobility device that can bolt-on
many of its instruments. The resulting files produce a new line in the scan
header with the term 'compensationVoltage', which is used to specify the
FAIMS setting for that scan. Can we add this term to the controlled
vocabulary please?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HUPO-PSI/psi-ms-CV/issues/22>, or mute the thread

**Comment by jgmeyerucsd** [comment]
Got it thanks for the quick reply
