### ISSUE TITLE
UNIMOD in OLS 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/psi-ms-CV#6]
@edeutsch @germa 

As we discussed in Beijing the Unimod Library has been added to OLS http://www.ebi.ac.uk/ols/ontologies/unimod This is one of the steps to move forward UNIMOD as a central place for Mass spectrometry Modifications. The guys from OLS would like that we improve the obo representation of unimod. But this is up to us. 

Regards 
Yasset

**Comment by edeutsch** [comment]
This is great, thanks. But I do not understand what you/they mean by
“improve the obo representation”. It would seem to be entirely sufficient
to me. I use it all the time. It includes allowed site information and
such. Maybe there are some things that are visible on the web site that are
not encoded in obo, but I have not found any that I needed. So it would
seem to me that what they currently produce is entirely adequate. But maybe
I’m missing something…



Eric





*From:* Yasset Perez-Riverol [mailto:notifications@github.com]
*Sent:* Monday, May 08, 2017 7:17 AM
*To:* HUPO-PSI/psi-ms-CV
*Cc:* Eric Deutsch; Mention
*Subject:* [HUPO-PSI/psi-ms-CV] UNIMOD in OLS (#6)



@edeutsch <https://github.com/edeutsch> @germa <https://github.com/germa>

As we discussed in Beijing the Unimod Library has been added to OLS
http://www.ebi.ac.uk/ols/ontologies/unimod This is one of the steps to move
forward UNIMOD as a central place for Mass spectrometry Modifications. The
guys from OLS would like that we improve the obo representation of unimod.
But this is up to us.

Regards
Yasset

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HUPO-PSI/psi-ms-CV/issues/6>, or mute the thread

**Comment by ypriverol** [comment]
Hi @edeutsch : 
 If you see this example: http://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0098743 

 compare with any of the Unimod examples, you will notice the difference. For example the **description** of the term is missing in UNIMOD, the xref is different also from other databases which actually are the properties of each modification. 

I will contact the guys from OLS @simonjupp that really knows from which fields in the obo file these xref are populated. 

Regards 
Yasset

**Comment by edeutsch** [comment]
Hmm, for example a UNIMOD term:



http://www.ebi.ac.uk/ols/ontologies/unimod/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUNIMOD_4



I see a def and a synonym all fine.



But the xrefs do seem to be a strangely rendered I suppose..



Maybe the heart of the problem is that they use the xref construction to
encode a lot of attributes of the term, which is not really intended by the
designers of obo. Maybe there’s a better way.



Note that we do the same thing in the MS ontology for encoding our
value-types:



http://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000858









*From:* Yasset Perez-Riverol [mailto:notifications@github.com]
*Sent:* Monday, May 08, 2017 1:21 PM
*To:* HUPO-PSI/psi-ms-CV
*Cc:* Eric Deutsch; Mention
*Subject:* Re: [HUPO-PSI/psi-ms-CV] UNIMOD in OLS (#6)



Hi @edeutsch <https://github.com/edeutsch> :
If you see this example:
http://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0098743

compare with any of the Unimod examples, you will notice the difference.
For example the *description* of the term is missing in UNIMOD, the xref is
different also from other databases which actually are the properties of
each modification.

I will contact the guys from OLS @simonjupp <https://github.com/simonjupp>
that really knows from which fields in the obo file these xref are
populated.

Regards
Yasset

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HUPO-PSI/psi-ms-CV/issues/6#issuecomment-299979272>,
or mute
the thread
