### ISSUE TITLE
Alternating polarity missing

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/psi-ms-CV#7]
Hi,

http://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000465 says 
"scan polarity is An acquisition mode to which specifies weather polarity is negative, positive or alternating.", 
but the children are only positive and negative. We are missing alternating.
Problem is that this is a single scan attribute, and a single scan can't be both.
Second question is if this is still a `is_a: MS:1000808 ! chromatogram attribute`,
as an alternating polarity SRM or MRM is pretty useless.

```
[Term]
id: MS:1000XXX
name: alternating polarity scans
def: "Polarity of the scans is alternating, i.e. both positive and negative scans present [PSI:MS]
is_a: MS:1000465 ! scan polarity
is_a: MS:1000808 ! chromatogram attribute
```

**Comment by edeutsch** [comment]
Hi Steffen, thanks for catching this. But a few points:
 
1) I think we should fix the grammar in the def of the parent term. “to which specifies weather” is nutty.
 
2) Actually it should probably be rewritten entirely to describe the concept of polarity. Maybe something like “relative orientation of the electromagnetic field during the selection and detection of ions in the mass spectrometer”. Is that even right? Any experts that can write a good definition?
 
3) I am skeptical that we need or want a term for alternating polarity. How will we use this? I think currently in most formats we tag each scan/spectrum with its polarity. Can a single scan have a polarity of “alternating”? Or would that be a general property of the ms run? If this is general property of an ms run, then this is a bit dangerous to put this here, because it would not be appropriate in most cases. If this is a pattern for an ms run, then perhaps it would be appropriate to have another parent term “polarity pattern”, with child terms “all positive polarity scans”, “all negative polarity scans”, “alternating polarity scans”, and “complex scan polarity pattern”, or something along those lines. And that tree would not be legal when tagging scans. Only when tagging ms runs as a whole. Which I don’t think we do.
 
Anyway, my suggestion is to think this through carefully and make sure we end up with a nice accurate set of terms that are appropriate for the contexts in which we use them.

What is you use case for "alternating polarity" specifically?
 
Thanks!
Eric

**Comment by chambm** [comment]
Alternating polarity would be a property of the instrument method, which mzML currently doesn't represent.

**Comment by sneumann** [comment]
Hi, the reason I brought this up was because ISA-Tab is describing the content of an mzML file, i.e. an attribute of the `<run>` as such being positive/negative/alternating. 
As indicated in my first comment, "alternating" can't be a scan attribute, but when I searched our obo for "alternating" that parent term came up. Maybe that was the reason why alternating was obsoleted:
https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L3241 
So a better home for "alternating polarity" could be "MS:1001954 acquisition parameter" (which currently has no children at all ?!) and which resides below the `<scanSettings>` of the mzML, 
which I think is the closest to describing the instrument method we can find in mzML.
The mapping file currently does not specify which CV terms can go below `<scanSettings>`.
I also realised we had obsoleted "ionization mode" https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo#L111 , which probably sounded a bad idea as scan attribute, but which might have been good to keep among the `<scanSettings>`.

So what about:

1) Grammar fix, plus removal of mentioning alternating as scan attribute:
```
[Term]
id: MS:1000465
name: scan polarity
def: "An acquisition mode to which specifies whether polarity is negative or positive." [PSI:MS]
relationship: part_of MS:1000441 ! scan
```

2) still add "alternating", but with different parent than proposed above:

```
[Term]
id: MS:1000XXX
name: alternating polarity mode
def: "Polarity of the scans is alternating, i.e. both positive and negative mode scans are acquired.[PSI:MS]
is_a: MS:1000009 ! ionization mode
```

3) Consider re-adding MS:1000009 ! ionization mode, but now as acquisition parameter (not sure what it was before):
```
[Term]
id: MS:1000009
name: ionization mode
def: "Whether positive or negative ions are selected for analysis by the spectrometer." [PSI:MS]
is_a: MS:1001954 ! acquisition parameter
```

**Comment by germa** [comment]
If the 'alternating polarity mode' is a property of a run, why not make it a children of 'run attribute'?

[Term]
id: MS:1000465
name: scan polarity
def: "Relative orientation of the electromagnetic field during the selection and detection of ions in the mass spectrometer." [PSI:MS]
relationship: part_of MS:1000441 ! scan

[Term]
id: MS:1002826
name: alternating polarity mode
def: "Polarities of the scans of a run are alternating, i.e. both positive and negative mode scans are acquired." [PSI:MS]
is_a: MS:1000857 ! run attribute

**Comment by germa** [comment]
done.
