### ISSUE TITLE
Proposed quantification datatype(s) for xcms

### ISSUE THREAD

**Issue by sneumann** [HUPO-PSI/psi-ms-CV#8]
Hi, psi-ms is missing the quantification datatype(s) for xcms
as child of http://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1002735

```
[Term]
id: MS:100XXXX
name: XCMS:into
def: "The data type feature intensity produced by XCMS findPeaks() from integrated peak intensity." [PSI:MS]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1002735 ! feature-level quantification datatype
```
```
[Term]
id: MS:100XXXX
name: XCMS:intf
def: "The data type feature intensity produced by XCMS findPeaks() from baseline corrected integrated peak intensity." [PSI:MS]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1002735 ! feature-level quantification datatype
```
```
[Term]
id: MS:100XXXX
name: XCMS:maxo
def: "The data type feature intensity produced by XCMS findPeaks() from maximum peak intensity." [PSI:MS]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1002735 ! feature-level quantification datatype
```
```
[Term]
id: MS:100XXXX
name: XCMS:area
def: "The data type feature intensity produced by XCMS findPeaks() from feature area that is not normalized by the scan rate." [PSI:MS]
xref: value-type:xsd\:double "The allowed value-type for this CV term."
is_a: MS:1002735 ! feature-level quantification datatype
```

**Comment by germa** [comment]
Hi Steffen,

in principle ok, but I propose to change the definitions, since data type can be misunderstood.

Why not just
def: "Feature intensity produced by XCMS findPeaks() from integrated peak intensity." [PSI:MS]
etc.

PS: What about the proposal
[Term]
id: MS:1002826
name: alternating polarity mode
def: "Polarities of the scans of a run are alternating, i.e. both positive and negative mode scans are acquired." [PSI:MS]
is_a: MS:1000857 ! run attribute

i.e. making 'alternating polarity mode' a child of 'run attribute' ?
see https://github.com/HUPO-PSI/psi-ms-CV/issues/7#issuecomment-324478232

**Comment by germa** [comment]
done.
